import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Toaster } from "react-hot-toast";
import Feed from "../components/Feed";
import Sidebar from "../components/Sidebar";
import Widgets from "../components/Widgets";
import { fetchTweets } from "../lib/fetchTweets";
import { Tweet } from "../typings";

interface Props {
  tweets: Tweet[];
}

const Home: any = ({ tweets }: Props) => {
  return (
    <div className="max-w-screen-xl mx-auto max-h-screen overflow-hidden">
      <Head>
        <title>Twitter Build</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Toaster />
      </div>

      <main className="grid grid-cols-9">
        <Sidebar />

        <Feed tweets={tweets} />

        <Widgets />
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const tweets = await fetchTweets();
  return {
    props: {
      tweets,
    }, // will be passed to the page component as props
  };
};
